# Generated by Django 4.2.7 on 2023-11-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titel',
            new_name='title',
        ),
    ]
